### ISSUE TITLE
✨ 검색 기능 구현

### ISSUE THREAD

**Issue by Moo-moo-11** [bean-space/bean-space#119]
# 기능 설명

검색 기능을 구현합니다

# To-do
- [x] 검색어를 입력하여 검색 및 검색어 저장
- [x] 검색 필터링 조건 강화
- [x] 편의 시설 리스트 만들기
