### ISSUE TITLE
✨오래된 검색어 정리 (스케줄러 설정)

### ISSUE THREAD

**Issue by DanDanjoo** [bean-space/bean-space#154]
# 기능 설명
스케줄러를 설정하여 매일 새벽 3시에 3일 이상 된 검색어를 삭제합니다.  

# To-do
- [ ] cron식 추가 ( 매일 새벽 3시에 실행하도록 )
- [ ] infra 패키지에 스케줄러 관련 로직 정의
- [ ] 3일 이상 된 검색어를 삭제하는 메서드 추가

# ETC
