### ISSUE TITLE
✨예약목록 확인 수정

### ISSUE THREAD

**Issue by DanDanjoo** [bean-space/bean-space#87]
# 기능 설명
프론트 구현을 위한 백엔드 예약목록 확인 수정

# To-do
- [x] 모든 예약 데이터 한 번에 가져오기 (체크아웃이 1년 이내?)
- [x] 리뷰 작성 여부, 취소여부 확인해서 같이 보내주기
- [x] 공간 listingName, 우편번호, 도로명주소, 상세주소

# ETC
