### ISSUE TITLE
✨ 쿠폰 발급 및 예약에 대한 동시성 제어 구현

### ISSUE THREAD

**Issue by Moo-moo-11** [bean-space/bean-space#93]
# 기능 설명

쿠폰 발급 및 예약에 대한 동시성 제어를 구현합니다

# To-do
- [ ] 분산 락 구현을 위한 Redis 설정하기
- [ ] 쿠폰 발급하기 기능에 분산 락 구현
- [ ] 공간 예약하기 기능에 분산 락 구현
- [ ] 테스트 코드 성공 여부 확인하기
