### ISSUE TITLE
✨ CI/CD 구축 작업

### ISSUE THREAD

**Issue by devitssu** [bean-space/bean-space#96]
# 기능 설명

github action을 이용하여 CI/CD 파이프라인 구축

# To-do
- AWS 설정
  - [x] RDS 설정
  - [x] Redis(EC2) 설정
  - [x] EB 설정
  - [x] 도메인 구입, Rout53 설정
- [x] Github Action 워크플로우 파일 작성
- [x] 환경변수 설정 ( 로컬, 운영 환경 분리 )
- [x] 동작 테스트

# ETC
